/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
<<<<<<< HEAD
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
=======
import { Route as LoginRouteImport } from './routes/login'
>>>>>>> 596041dd872ed2d87ec020683ec940e19571c71c
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VerifyIdRouteImport } from './routes/verify.$id'
import { Route as AuthenticatedWorkshopRouteImport } from './routes/_authenticated/workshop'
import { Route as AuthenticatedVolunteersRouteImport } from './routes/_authenticated/volunteers'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedScannerRouteImport } from './routes/_authenticated/scanner'
<<<<<<< HEAD
import { Route as AuthenticatedOrganizationSetupRouteImport } from './routes/_authenticated/organization-setup'
=======
>>>>>>> 596041dd872ed2d87ec020683ec940e19571c71c
import { Route as AuthenticatedMealScannerRouteImport } from './routes/_authenticated/meal-scanner'
import { Route as AuthenticatedExitRouteImport } from './routes/_authenticated/exit'
import { Route as AuthenticatedEntryRouteImport } from './routes/_authenticated/entry'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCustomFolderRouteImport } from './routes/_authenticated/custom-folder'
import { Route as AuthenticatedCulturalRouteImport } from './routes/_authenticated/cultural'
import { Route as AuthenticatedAdventureRouteImport } from './routes/_authenticated/adventure'
import { Route as AuthenticatedCheckIdRouteImport } from './routes/_authenticated/check.$id'

<<<<<<< HEAD
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
=======
>>>>>>> 596041dd872ed2d87ec020683ec940e19571c71c
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
<<<<<<< HEAD
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
=======
>>>>>>> 596041dd872ed2d87ec020683ec940e19571c71c
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyIdRoute = VerifyIdRouteImport.update({
  id: '/verify/$id',
  path: '/verify/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWorkshopRoute = AuthenticatedWorkshopRouteImport.update({
  id: '/workshop',
  path: '/workshop',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedVolunteersRoute = AuthenticatedVolunteersRouteImport.update({
  id: '/volunteers',
  path: '/volunteers',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedScannerRoute = AuthenticatedScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => AuthenticatedRoute,
} as any)
<<<<<<< HEAD
const AuthenticatedOrganizationSetupRoute =
  AuthenticatedOrganizationSetupRouteImport.update({
    id: '/organization-setup',
    path: '/organization-setup',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
=======
>>>>>>> 596041dd872ed2d87ec020683ec940e19571c71c
const AuthenticatedMealScannerRoute =
  AuthenticatedMealScannerRouteImport.update({
    id: '/meal-scanner',
    path: '/meal-scanner',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedExitRoute = AuthenticatedExitRouteImport.update({
  id: '/exit',
  path: '/exit',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEntryRoute = AuthenticatedEntryRouteImport.update({
  id: '/entry',
  path: '/entry',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCustomFolderRoute =
  AuthenticatedCustomFolderRouteImport.update({
    id: '/custom-folder',
    path: '/custom-folder',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCulturalRoute = AuthenticatedCulturalRouteImport.update({
  id: '/cultural',
  path: '/cultural',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdventureRoute = AuthenticatedAdventureRouteImport.update({
  id: '/adventure',
  path: '/adventure',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCheckIdRoute = AuthenticatedCheckIdRouteImport.update({
  id: '/check/$id',
  path: '/check/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
<<<<<<< HEAD
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
=======
  '/login': typeof LoginRoute
>>>>>>> 596041dd872ed2d87ec020683ec940e19571c71c
  '/adventure': typeof AuthenticatedAdventureRoute
  '/cultural': typeof AuthenticatedCulturalRoute
  '/custom-folder': typeof AuthenticatedCustomFolderRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/entry': typeof AuthenticatedEntryRoute
  '/exit': typeof AuthenticatedExitRoute
  '/meal-scanner': typeof AuthenticatedMealScannerRoute
<<<<<<< HEAD
  '/organization-setup': typeof AuthenticatedOrganizationSetupRoute
=======
>>>>>>> 596041dd872ed2d87ec020683ec940e19571c71c
  '/scanner': typeof AuthenticatedScannerRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/volunteers': typeof AuthenticatedVolunteersRoute
  '/workshop': typeof AuthenticatedWorkshopRoute
  '/verify/$id': typeof VerifyIdRoute
  '/check/$id': typeof AuthenticatedCheckIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
<<<<<<< HEAD
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
=======
  '/login': typeof LoginRoute
>>>>>>> 596041dd872ed2d87ec020683ec940e19571c71c
  '/adventure': typeof AuthenticatedAdventureRoute
  '/cultural': typeof AuthenticatedCulturalRoute
  '/custom-folder': typeof AuthenticatedCustomFolderRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/entry': typeof AuthenticatedEntryRoute
  '/exit': typeof AuthenticatedExitRoute
  '/meal-scanner': typeof AuthenticatedMealScannerRoute
<<<<<<< HEAD
  '/organization-setup': typeof AuthenticatedOrganizationSetupRoute
=======
>>>>>>> 596041dd872ed2d87ec020683ec940e19571c71c
  '/scanner': typeof AuthenticatedScannerRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/volunteers': typeof AuthenticatedVolunteersRoute
  '/workshop': typeof AuthenticatedWorkshopRoute
  '/verify/$id': typeof VerifyIdRoute
  '/check/$id': typeof AuthenticatedCheckIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
<<<<<<< HEAD
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
=======
  '/login': typeof LoginRoute
>>>>>>> 596041dd872ed2d87ec020683ec940e19571c71c
  '/_authenticated/adventure': typeof AuthenticatedAdventureRoute
  '/_authenticated/cultural': typeof AuthenticatedCulturalRoute
  '/_authenticated/custom-folder': typeof AuthenticatedCustomFolderRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/entry': typeof AuthenticatedEntryRoute
  '/_authenticated/exit': typeof AuthenticatedExitRoute
  '/_authenticated/meal-scanner': typeof AuthenticatedMealScannerRoute
<<<<<<< HEAD
  '/_authenticated/organization-setup': typeof AuthenticatedOrganizationSetupRoute
=======
>>>>>>> 596041dd872ed2d87ec020683ec940e19571c71c
  '/_authenticated/scanner': typeof AuthenticatedScannerRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/volunteers': typeof AuthenticatedVolunteersRoute
  '/_authenticated/workshop': typeof AuthenticatedWorkshopRoute
  '/verify/$id': typeof VerifyIdRoute
  '/_authenticated/check/$id': typeof AuthenticatedCheckIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
<<<<<<< HEAD
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
=======
    | '/login'
>>>>>>> 596041dd872ed2d87ec020683ec940e19571c71c
    | '/adventure'
    | '/cultural'
    | '/custom-folder'
    | '/dashboard'
    | '/entry'
    | '/exit'
    | '/meal-scanner'
<<<<<<< HEAD
    | '/organization-setup'
=======
>>>>>>> 596041dd872ed2d87ec020683ec940e19571c71c
    | '/scanner'
    | '/settings'
    | '/volunteers'
    | '/workshop'
    | '/verify/$id'
    | '/check/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
<<<<<<< HEAD
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
=======
    | '/login'
>>>>>>> 596041dd872ed2d87ec020683ec940e19571c71c
    | '/adventure'
    | '/cultural'
    | '/custom-folder'
    | '/dashboard'
    | '/entry'
    | '/exit'
    | '/meal-scanner'
<<<<<<< HEAD
    | '/organization-setup'
=======
>>>>>>> 596041dd872ed2d87ec020683ec940e19571c71c
    | '/scanner'
    | '/settings'
    | '/volunteers'
    | '/workshop'
    | '/verify/$id'
    | '/check/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
<<<<<<< HEAD
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
=======
    | '/login'
>>>>>>> 596041dd872ed2d87ec020683ec940e19571c71c
    | '/_authenticated/adventure'
    | '/_authenticated/cultural'
    | '/_authenticated/custom-folder'
    | '/_authenticated/dashboard'
    | '/_authenticated/entry'
    | '/_authenticated/exit'
    | '/_authenticated/meal-scanner'
<<<<<<< HEAD
    | '/_authenticated/organization-setup'
=======
>>>>>>> 596041dd872ed2d87ec020683ec940e19571c71c
    | '/_authenticated/scanner'
    | '/_authenticated/settings'
    | '/_authenticated/volunteers'
    | '/_authenticated/workshop'
    | '/verify/$id'
    | '/_authenticated/check/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
<<<<<<< HEAD
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
=======
  LoginRoute: typeof LoginRoute
>>>>>>> 596041dd872ed2d87ec020683ec940e19571c71c
  VerifyIdRoute: typeof VerifyIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
<<<<<<< HEAD
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
=======
>>>>>>> 596041dd872ed2d87ec020683ec940e19571c71c
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
<<<<<<< HEAD
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
=======
>>>>>>> 596041dd872ed2d87ec020683ec940e19571c71c
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$id': {
      id: '/verify/$id'
      path: '/verify/$id'
      fullPath: '/verify/$id'
      preLoaderRoute: typeof VerifyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/workshop': {
      id: '/_authenticated/workshop'
      path: '/workshop'
      fullPath: '/workshop'
      preLoaderRoute: typeof AuthenticatedWorkshopRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/volunteers': {
      id: '/_authenticated/volunteers'
      path: '/volunteers'
      fullPath: '/volunteers'
      preLoaderRoute: typeof AuthenticatedVolunteersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/scanner': {
      id: '/_authenticated/scanner'
      path: '/scanner'
      fullPath: '/scanner'
      preLoaderRoute: typeof AuthenticatedScannerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
<<<<<<< HEAD
    '/_authenticated/organization-setup': {
      id: '/_authenticated/organization-setup'
      path: '/organization-setup'
      fullPath: '/organization-setup'
      preLoaderRoute: typeof AuthenticatedOrganizationSetupRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
=======
>>>>>>> 596041dd872ed2d87ec020683ec940e19571c71c
    '/_authenticated/meal-scanner': {
      id: '/_authenticated/meal-scanner'
      path: '/meal-scanner'
      fullPath: '/meal-scanner'
      preLoaderRoute: typeof AuthenticatedMealScannerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/exit': {
      id: '/_authenticated/exit'
      path: '/exit'
      fullPath: '/exit'
      preLoaderRoute: typeof AuthenticatedExitRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/entry': {
      id: '/_authenticated/entry'
      path: '/entry'
      fullPath: '/entry'
      preLoaderRoute: typeof AuthenticatedEntryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/custom-folder': {
      id: '/_authenticated/custom-folder'
      path: '/custom-folder'
      fullPath: '/custom-folder'
      preLoaderRoute: typeof AuthenticatedCustomFolderRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cultural': {
      id: '/_authenticated/cultural'
      path: '/cultural'
      fullPath: '/cultural'
      preLoaderRoute: typeof AuthenticatedCulturalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/adventure': {
      id: '/_authenticated/adventure'
      path: '/adventure'
      fullPath: '/adventure'
      preLoaderRoute: typeof AuthenticatedAdventureRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/check/$id': {
      id: '/_authenticated/check/$id'
      path: '/check/$id'
      fullPath: '/check/$id'
      preLoaderRoute: typeof AuthenticatedCheckIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdventureRoute: typeof AuthenticatedAdventureRoute
  AuthenticatedCulturalRoute: typeof AuthenticatedCulturalRoute
  AuthenticatedCustomFolderRoute: typeof AuthenticatedCustomFolderRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEntryRoute: typeof AuthenticatedEntryRoute
  AuthenticatedExitRoute: typeof AuthenticatedExitRoute
  AuthenticatedMealScannerRoute: typeof AuthenticatedMealScannerRoute
<<<<<<< HEAD
  AuthenticatedOrganizationSetupRoute: typeof AuthenticatedOrganizationSetupRoute
=======
>>>>>>> 596041dd872ed2d87ec020683ec940e19571c71c
  AuthenticatedScannerRoute: typeof AuthenticatedScannerRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedVolunteersRoute: typeof AuthenticatedVolunteersRoute
  AuthenticatedWorkshopRoute: typeof AuthenticatedWorkshopRoute
  AuthenticatedCheckIdRoute: typeof AuthenticatedCheckIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdventureRoute: AuthenticatedAdventureRoute,
  AuthenticatedCulturalRoute: AuthenticatedCulturalRoute,
  AuthenticatedCustomFolderRoute: AuthenticatedCustomFolderRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEntryRoute: AuthenticatedEntryRoute,
  AuthenticatedExitRoute: AuthenticatedExitRoute,
  AuthenticatedMealScannerRoute: AuthenticatedMealScannerRoute,
<<<<<<< HEAD
  AuthenticatedOrganizationSetupRoute: AuthenticatedOrganizationSetupRoute,
=======
>>>>>>> 596041dd872ed2d87ec020683ec940e19571c71c
  AuthenticatedScannerRoute: AuthenticatedScannerRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedVolunteersRoute: AuthenticatedVolunteersRoute,
  AuthenticatedWorkshopRoute: AuthenticatedWorkshopRoute,
  AuthenticatedCheckIdRoute: AuthenticatedCheckIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
<<<<<<< HEAD
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  VerifyEmailRoute: VerifyEmailRoute,
=======
  LoginRoute: LoginRoute,
>>>>>>> 596041dd872ed2d87ec020683ec940e19571c71c
  VerifyIdRoute: VerifyIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
