/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VerifyIdRouteImport } from './routes/verify.$id'
import { Route as AuthenticatedWorkshopRouteImport } from './routes/_authenticated/workshop'
import { Route as AuthenticatedVolunteersRouteImport } from './routes/_authenticated/volunteers'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedScannerRouteImport } from './routes/_authenticated/scanner'
import { Route as AuthenticatedMealScannerRouteImport } from './routes/_authenticated/meal-scanner'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCulturalRouteImport } from './routes/_authenticated/cultural'
import { Route as AuthenticatedAdventureRouteImport } from './routes/_authenticated/adventure'
import { Route as AuthenticatedCheckIdRouteImport } from './routes/_authenticated/check.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyIdRoute = VerifyIdRouteImport.update({
  id: '/verify/$id',
  path: '/verify/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWorkshopRoute = AuthenticatedWorkshopRouteImport.update({
  id: '/workshop',
  path: '/workshop',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedVolunteersRoute = AuthenticatedVolunteersRouteImport.update({
  id: '/volunteers',
  path: '/volunteers',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedScannerRoute = AuthenticatedScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMealScannerRoute =
  AuthenticatedMealScannerRouteImport.update({
    id: '/meal-scanner',
    path: '/meal-scanner',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCulturalRoute = AuthenticatedCulturalRouteImport.update({
  id: '/cultural',
  path: '/cultural',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdventureRoute = AuthenticatedAdventureRouteImport.update({
  id: '/adventure',
  path: '/adventure',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCheckIdRoute = AuthenticatedCheckIdRouteImport.update({
  id: '/check/$id',
  path: '/check/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/adventure': typeof AuthenticatedAdventureRoute
  '/cultural': typeof AuthenticatedCulturalRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/meal-scanner': typeof AuthenticatedMealScannerRoute
  '/scanner': typeof AuthenticatedScannerRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/volunteers': typeof AuthenticatedVolunteersRoute
  '/workshop': typeof AuthenticatedWorkshopRoute
  '/verify/$id': typeof VerifyIdRoute
  '/check/$id': typeof AuthenticatedCheckIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/adventure': typeof AuthenticatedAdventureRoute
  '/cultural': typeof AuthenticatedCulturalRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/meal-scanner': typeof AuthenticatedMealScannerRoute
  '/scanner': typeof AuthenticatedScannerRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/volunteers': typeof AuthenticatedVolunteersRoute
  '/workshop': typeof AuthenticatedWorkshopRoute
  '/verify/$id': typeof VerifyIdRoute
  '/check/$id': typeof AuthenticatedCheckIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/adventure': typeof AuthenticatedAdventureRoute
  '/_authenticated/cultural': typeof AuthenticatedCulturalRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/meal-scanner': typeof AuthenticatedMealScannerRoute
  '/_authenticated/scanner': typeof AuthenticatedScannerRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/volunteers': typeof AuthenticatedVolunteersRoute
  '/_authenticated/workshop': typeof AuthenticatedWorkshopRoute
  '/verify/$id': typeof VerifyIdRoute
  '/_authenticated/check/$id': typeof AuthenticatedCheckIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/adventure'
    | '/cultural'
    | '/dashboard'
    | '/meal-scanner'
    | '/scanner'
    | '/settings'
    | '/volunteers'
    | '/workshop'
    | '/verify/$id'
    | '/check/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/adventure'
    | '/cultural'
    | '/dashboard'
    | '/meal-scanner'
    | '/scanner'
    | '/settings'
    | '/volunteers'
    | '/workshop'
    | '/verify/$id'
    | '/check/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/adventure'
    | '/_authenticated/cultural'
    | '/_authenticated/dashboard'
    | '/_authenticated/meal-scanner'
    | '/_authenticated/scanner'
    | '/_authenticated/settings'
    | '/_authenticated/volunteers'
    | '/_authenticated/workshop'
    | '/verify/$id'
    | '/_authenticated/check/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  VerifyIdRoute: typeof VerifyIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$id': {
      id: '/verify/$id'
      path: '/verify/$id'
      fullPath: '/verify/$id'
      preLoaderRoute: typeof VerifyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/workshop': {
      id: '/_authenticated/workshop'
      path: '/workshop'
      fullPath: '/workshop'
      preLoaderRoute: typeof AuthenticatedWorkshopRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/volunteers': {
      id: '/_authenticated/volunteers'
      path: '/volunteers'
      fullPath: '/volunteers'
      preLoaderRoute: typeof AuthenticatedVolunteersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/scanner': {
      id: '/_authenticated/scanner'
      path: '/scanner'
      fullPath: '/scanner'
      preLoaderRoute: typeof AuthenticatedScannerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/meal-scanner': {
      id: '/_authenticated/meal-scanner'
      path: '/meal-scanner'
      fullPath: '/meal-scanner'
      preLoaderRoute: typeof AuthenticatedMealScannerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cultural': {
      id: '/_authenticated/cultural'
      path: '/cultural'
      fullPath: '/cultural'
      preLoaderRoute: typeof AuthenticatedCulturalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/adventure': {
      id: '/_authenticated/adventure'
      path: '/adventure'
      fullPath: '/adventure'
      preLoaderRoute: typeof AuthenticatedAdventureRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/check/$id': {
      id: '/_authenticated/check/$id'
      path: '/check/$id'
      fullPath: '/check/$id'
      preLoaderRoute: typeof AuthenticatedCheckIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdventureRoute: typeof AuthenticatedAdventureRoute
  AuthenticatedCulturalRoute: typeof AuthenticatedCulturalRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMealScannerRoute: typeof AuthenticatedMealScannerRoute
  AuthenticatedScannerRoute: typeof AuthenticatedScannerRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedVolunteersRoute: typeof AuthenticatedVolunteersRoute
  AuthenticatedWorkshopRoute: typeof AuthenticatedWorkshopRoute
  AuthenticatedCheckIdRoute: typeof AuthenticatedCheckIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdventureRoute: AuthenticatedAdventureRoute,
  AuthenticatedCulturalRoute: AuthenticatedCulturalRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMealScannerRoute: AuthenticatedMealScannerRoute,
  AuthenticatedScannerRoute: AuthenticatedScannerRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedVolunteersRoute: AuthenticatedVolunteersRoute,
  AuthenticatedWorkshopRoute: AuthenticatedWorkshopRoute,
  AuthenticatedCheckIdRoute: AuthenticatedCheckIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  VerifyIdRoute: VerifyIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
